"use client";

import { useEffect, useRef } from "react";
import { fetchAlertHistory, fetchAlertRules } from "@/lib/services/alertRulesService";
import { subscribeToAllCamerasFeed } from "@/lib/allCamerasFeed";
import {
  absenceEventDurationSeconds,
  absenceThresholdSeconds,
  isAbsenceResolvedEvent,
  isAbsenceRule,
  isZoneScopedAbsenceRule,
} from "@/lib/alertConditions";
import { extractPersonBoxes, intersects, normalizeRuleRegion } from "@/lib/detectionBoxes";
import { useAlertPresenceStore } from "@/lib/store/useAlertPresenceStore";
import type { AlertRuleV2 } from "@/lib/types";

const RULES_REFRESH_MS = 15_000;
// Frequent enough that even the shortest allowed threshold (1 min) fires
// within a few seconds of crossing it, without evaluating on every single
// websocket message.
const CHECK_INTERVAL_MS = 10_000;
// No people_count message for a camera this long means the camera itself
// isn't reporting — a different problem ("no signal") from "no person",
// already surfaced elsewhere via useCameras()/useStableCameraStatus. An
// absence rule must never fire (or show "empty") just because a camera
// went dark.
const FEED_STALE_MS = 120_000;

type UnknownRecord = Record<string, unknown>;
function asRecord(value: unknown): UnknownRecord {
  return value && typeof value === "object" ? (value as UnknownRecord) : {};
}

interface CameraPresenceState {
  /** Local ms clock at the last people_count message of any count — the liveness signal. */
  lastMessageAtMs: number;
  /** Most recent event_id for this camera (captured from every message, zero-count included) — the only frame reference an absence match can cite. */
  lastEventId: string | null;
}

/**
 * Browser-side live-status tracker for "no person detected" rules.
 *
 * Alert event creation is intentionally owned by `sync-service/index.js`
 * (`evaluateAbsenceRules`) so absence alerts continue to fire 24/7 when no
 * dashboard browser tab is open. This hook only feeds the in-memory
 * `useAlertPresenceStore` used by live UI labels.
 *
 * Handles two rule shapes, both stored as `conditions.condition === "absence"`:
 *  - Frame-wide (no bounding box): any person anywhere in frame counts as
 *    presence, tracked cheaply from the fleet-wide `people_count` feed alone.
 *  - Zone-scoped ("Restricted Zone", has a bounding box): only a person
 *    detected *inside that region* counts, which needs the same
 *    fetch-and-intersect approach `useAlertWatcher` uses for region alerts.
 *
 * Publishes each watched rule's "absent since" timestamp (and, once an
 * absence episode ends, its total duration) to `useAlertPresenceStore` so
 * `AbsenceLiveStatus` can render a continuously ticking status.
 *
 * A rule's in-memory timers reset on every page reload, so on first seeing
 * a rule each session this hook bootstraps its state from that rule's own
 * server-side match history (see `isAbsenceResolvedEvent`/
 * `absenceEventDurationSeconds` in `alertConditions.ts`) instead of always
 * starting from "now" — otherwise a reload mid-absence would silently
 * truncate the episode and its eventual "resolved" duration would be wrong.
 *
 * Known gap: a camera whose stream is frozen but whose worker still emits
 * zero-count messages is indistinguishable from a genuinely empty room/zone.
 */
export function useNoPersonWatcher() {
  const rulesRef = useRef<AlertRuleV2[]>([]);
  const cameraStateRef = useRef<Map<string, CameraPresenceState>>(new Map());
  // Per alertId: ms clock at which the current continuous absence began —
  // the single source of truth for "how long has this rule been empty",
  // for both frame-wide and zone-scoped rules alike.
  const absentSinceRef = useRef<Map<string, number>>(new Map());
  // Per alertId: has this rule crossed its threshold at least once during
  // the current absence episode? This only controls the browser's live
  // "was absent for X" status; persistent alert events are generated by
  // the server-side sync service.
  const alertingRef = useRef<Map<string, boolean>>(new Map());
  const lastFiredAtRef = useRef<Map<string, number>>(new Map());

  // Zustand action references are stable across renders, but routed through
  // refs anyway so the two effects below can keep empty dependency arrays,
  // matching this file's existing all-state-in-refs idiom.
  const setLastPersonAtRef = useRef(useAlertPresenceStore.getState().setLastPersonAt);
  const setLastResolvedDurationRef = useRef(useAlertPresenceStore.getState().setLastResolvedDuration);
  const clearRuleRef = useRef(useAlertPresenceStore.getState().clearRule);

  useEffect(() => {
    let cancelled = false;

    // First time this session a rule is seen: recover its true state from
    // its own history rather than assuming a fresh start. Seeds a
    // provisional "just armed" state immediately so evaluate()/the live
    // display never see a gap while the fetch below is in flight.
    async function bootstrapRuleState(rule: AlertRuleV2) {
      const armedAt = Date.now();
      absentSinceRef.current.set(rule.alertId, armedAt);
      alertingRef.current.set(rule.alertId, false);
      setLastPersonAtRef.current(rule.alertId, armedAt);

      try {
        const history = await fetchAlertHistory(rule.alertId);
        if (cancelled) return;
        const latest = [...history].sort((a, b) => {
          const aMs = Date.parse(a.detectionTs ?? a.createdAt ?? "") || 0;
          const bMs = Date.parse(b.detectionTs ?? b.createdAt ?? "") || 0;
          return bMs - aMs;
        })[0];
        if (!latest) return; // no history yet — provisional "just armed" seed stands

        if (isAbsenceResolvedEvent(latest)) {
          // Most recent known state was already "resolved" — surface that
          // duration immediately instead of showing a blank live status.
          setLastResolvedDurationRef.current(rule.alertId, absenceEventDurationSeconds(latest));
          return;
        }

        // Latest event is an unresolved "still absent" fire — reconstruct
        // the true episode start from its own recorded elapsed-at-fire
        // value, so a reload mid-absence doesn't reset the clock.
        const eventMs = Date.parse(latest.detectionTs ?? latest.createdAt ?? "") || armedAt;
        const reconstructedStart = eventMs - absenceEventDurationSeconds(latest) * 1000;
        absentSinceRef.current.set(rule.alertId, reconstructedStart);
        alertingRef.current.set(rule.alertId, true);
        lastFiredAtRef.current.set(rule.alertId, eventMs);
        setLastPersonAtRef.current(rule.alertId, reconstructedStart);
      } catch {
        // Keep the provisional "just armed" seed — best effort.
      }
    }

    async function refreshRules() {
      try {
        const rules = await fetchAlertRules({ status: "active" });
        if (cancelled) return;
        rulesRef.current = rules.filter(isAbsenceRule);

        // Prune state for rules that left the active set (muted, resolved,
        // deleted) so a later reactivation re-arms from scratch instead of
        // firing instantly on stale bookkeeping.
        const liveIds = new Set(rulesRef.current.map((rule) => rule.alertId));
        for (const alertId of [...absentSinceRef.current.keys()]) {
          if (!liveIds.has(alertId)) {
            absentSinceRef.current.delete(alertId);
            alertingRef.current.delete(alertId);
            lastFiredAtRef.current.delete(alertId);
            clearRuleRef.current(alertId);
          }
        }
        for (const rule of rulesRef.current) {
          if (!absentSinceRef.current.has(rule.alertId)) {
            void bootstrapRuleState(rule);
          }
        }
      } catch {
        // Keep the previous rule set if a refresh fails; the next tick retries.
      }
    }

    refreshRules();
    const interval = setInterval(refreshRules, RULES_REFRESH_MS);
    return () => {
      cancelled = true;
      clearInterval(interval);
    };
  }, []);

  useEffect(() => {
    // Presence (re)detected for a rule — resets its absence timer, and if
    // it had crossed the threshold during this absence episode, records the
    // completed duration in browser state for display.
    function markPresence(rule: AlertRuleV2, now: number) {
      const wasAlerting = alertingRef.current.get(rule.alertId) ?? false;
      if (wasAlerting) {
        const absentSince = absentSinceRef.current.get(rule.alertId) ?? now;
        const durationSeconds = Math.round((now - absentSince) / 1000);
        alertingRef.current.set(rule.alertId, false);
        lastFiredAtRef.current.delete(rule.alertId);
        setLastResolvedDurationRef.current(rule.alertId, durationSeconds);
      }
      absentSinceRef.current.set(rule.alertId, now);
      setLastPersonAtRef.current(rule.alertId, now);
    }

    // Zone-scoped rules need the same event-detail fetch + intersection test
    // `useAlertWatcher` uses, just inverted: we're tracking the last time a
    // person WAS inside the region, not firing the moment one is.
    async function checkZoneRules(cameraId: string, eventId: string) {
      const zoneRules = rulesRef.current.filter(
        (rule) => isZoneScopedAbsenceRule(rule) && rule.cameraId.toLowerCase() === cameraId
      );
      if (zoneRules.length === 0) return;

      const response = await fetch(`/api/events/${encodeURIComponent(eventId)}`, {
        cache: "no-store",
      }).catch(() => null);
      if (!response?.ok) return;
      const personBoxes = extractPersonBoxes(asRecord(await response.json()));
      if (personBoxes.length === 0) return;

      const now = Date.now();
      for (const rule of zoneRules) {
        const region = normalizeRuleRegion(rule);
        if (!region) continue;
        const personInZone = personBoxes.some((box) => intersects(box, region));
        if (!personInZone) continue;
        markPresence(rule, now);
      }
    }

    function evaluate() {
      const now = Date.now();
      for (const rule of rulesRef.current) {
        const cameraState = cameraStateRef.current.get(rule.cameraId.toLowerCase());
        if (!cameraState) continue; // never observed this camera yet
        if (now - cameraState.lastMessageAtMs > FEED_STALE_MS) continue; // camera not reporting — not "no person"

        const absentSince = absentSinceRef.current.get(rule.alertId) ?? now;
        const thresholdMs = absenceThresholdSeconds(rule) * 1000;
        const elapsedMs = now - absentSince;

        // Keep the live-status store fresh even on ticks that don't fire.
        setLastPersonAtRef.current(rule.alertId, absentSince);

        if (elapsedMs < thresholdMs) continue;

        const lastFired = lastFiredAtRef.current.get(rule.alertId) ?? 0;
        if (now - lastFired < thresholdMs) continue; // repeat cadence not due yet

        lastFiredAtRef.current.set(rule.alertId, now);
        alertingRef.current.set(rule.alertId, true);
      }
    }

    const timer = setInterval(evaluate, CHECK_INTERVAL_MS);

    const unsubscribe = subscribeToAllCamerasFeed((data) => {
      if (data.type !== "people_count") return;
      const cameraId = String(data.camera_id ?? "").toLowerCase();
      const peopleCount = Number(data.people_count);
      if (!cameraId || !Number.isFinite(peopleCount)) return;

      const now = Date.now();
      const eventId = String(data.event_id ?? "") || null;
      const prevCamera = cameraStateRef.current.get(cameraId);

      // No message from this camera in a while — we have no evidence about
      // what happened during the gap, so re-arm every rule on it silently
      // (no "resolved" event, since we don't actually know a person
      // returned) rather than either assuming continued absence (which
      // would let a multi-hour outage look like a multi-hour empty room)
      // or assuming presence.
      const resumedAfterGap = !prevCamera || now - prevCamera.lastMessageAtMs > FEED_STALE_MS;

      cameraStateRef.current.set(cameraId, {
        lastMessageAtMs: now,
        lastEventId: eventId ?? prevCamera?.lastEventId ?? null,
      });

      if (resumedAfterGap) {
        for (const rule of rulesRef.current) {
          if (rule.cameraId.toLowerCase() !== cameraId) continue;
          absentSinceRef.current.set(rule.alertId, now);
          alertingRef.current.set(rule.alertId, false);
          setLastPersonAtRef.current(rule.alertId, now);
        }
      } else if (peopleCount > 0) {
        for (const rule of rulesRef.current) {
          if (!isZoneScopedAbsenceRule(rule) && rule.cameraId.toLowerCase() === cameraId) {
            markPresence(rule, now);
          }
        }
      }

      if (eventId) void checkZoneRules(cameraId, eventId);
    });

    return () => {
      unsubscribe();
      clearInterval(timer);
    };
  }, []);
}
